dist: bionic

addons:
  chrome: stable

node_js:
  - "12"

cache:
  directories:
     - ./node_modules

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn test_lib --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
  - codecov
